### ISSUE TITLE
It's not possible to configure iaqualink sensor by adding platform: iaqualink 

### ISSUE THREAD

**Issue by SanderM2** [galletn/iaqualink#10]
When adding the configuration like suggested I get this error message:

Unused YAML configuration for the iaqualink integration

It's not possible to configure iaqualink sensor by adding platform: iaqualink to the sensor configuration. Please check the documentation for more information on how to set up this integration.

To resolve this:

Remove platform: iaqualink occurences from the sensor: configuration in your YAML configuration file.
Restart Home Assistant.
Example that should be removed:

sensor:
  - platform: iaqualink

**Comment by SanderM2** [comment]
Oh. Never mind. The configuration example on the HACS page is incorrect/outdated.
The example shown on github is fine ;)

**Comment by galletn** [comment]
fixed in latest patch
