### ISSUE TITLE
Not an issue : RA 6900 iQ is working

### ISSUE THREAD

**Issue by tmenguy** [galletn/iaqualink#12]
Thanks for your great work, just to confirm : it works for this robot too :) Thanks for your work

**Comment by tmenguy** [comment]
And once I'm at it, I've seen some nice cards in some of the issues, any possibility to get their YAML in the documentation?

**Comment by galletn** [comment]
Added it to the info thanks for your feedback! I'll see if I can add my YAML, and that of some others to the readme info!
