### ISSUE TITLE
Zodiac CNX 30 iQ request

### ISSUE THREAD

**Issue by falinka** [galletn/iaqualink#19]
Hi,

Would there be any chance to extend the supported models list with additional robots?

As others mentioned, plugin works fine, connects, but that's about it.

Serial number: xxxxxxxxxxx
Robot name: Pool robot
Last online: 4 June 2024 at 11:12:03
Temperature: 0
Pressure: N/A
Total hours: 0
Error state: N/A
Lift control: N/A
Equipment ID: N/A
Cycle start time: 1 January 2000 at 09:00:00
Canister: N/A
Running: N/A
Model: CNX 30 iQ

**Comment by galletn** [comment]
Someone of you will need to have some more deep knowledge of tracing what API's your robot consults.

The issues lies in the fact that not all robots seem to consume the same API's, thus resulting in less data then others.

If you can get the API's I'm more then willing to add them to the code.

**Comment by falinka** [comment]
How about if I share user/pass with you? :) I can do some basic things, but can easily follow guides, if it can help.

**Comment by falinka** [comment]
So, i managed to grab entire communication using Fiddler Proxy. I could attach the file here, but it has quite a lot of personal info. Also, i have 2 exports, one is text file, which has basic things, and second is some fiddler specific export, which should in theory contain more data.

**Comment by galletn** [comment]
you can send them to me by mail if you want. I'll try to have a look, but can't promise a timeline for now.

**Comment by falinka** [comment]
Done. Let me know if you need something extra. No rush on the timeline though :)
