### ISSUE TITLE
incompatibility warning for "using deprecated supported features values" 

### ISSUE THREAD

**Issue by tmenguy** [galletn/iaqualink#24]
Hi, 

Fantastic the new web socket API connection ... neat

Got this in my logs (latest HA)

Entity vacuum.peyrebelle_pool_robot (<class 'custom_components.iaqualinkRobots.vacuum.IAquaLinkRobotVacuum'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.STOP|START: 8200>, please create a bug report at https://github.com/galletn/iaqualink/issues/ and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by galletn** [comment]
yes, this one is on my radar that I need to change it, but did not find the time yet. thanks for logging it!

**Comment by galletn** [comment]
will be resolved in next patch update

**Comment by tmenguy** [comment]
thx!
