### ISSUE TITLE
The version eec1b3e for this integration can not be used with HACS.

### ISSUE THREAD

**Issue by OtisPresley** [galletn/iaqualink#36]
This error occurs when trying to download the integration in HACS 2.0.0. It does not offer a selection for which version to download.

**Comment by galletn** [comment]
let me check, did not upgrade to HACS 2.0.0 yet and I will also check to have a clear version name! thanks for logging it!

**Comment by galletn** [comment]
Should be fixed now!

<img width="1707" alt="image" src="https://github.com/user-attachments/assets/4aa1d960-e0a2-4873-893d-a1a25aaaa5f1">


<img width="402" alt="image" src="https://github.com/user-attachments/assets/5b433ebc-a530-45b7-b20b-41b61ce88d89">

**Comment by OtisPresley** [comment]
Thanks @galletn! I have confirmed that I can now download the addon.
