### ISSUE TITLE
Robot pool type "vr" cycle information

### ISSUE THREAD

**Issue by DeltaFox0018** [galletn/iaqualink#37]
Hi,

Hello,
I have the following robot RA 6500 iQ and once configured as device type I have “vr”

As you can see from the screenshot start and end cycle are the same although by default when run from the app on the phone or directly from its base the duration is 2 hours and 30 minutes

Do you know how come I could have this problem?
Otherwise everything works

<img width="566" alt="image" src="https://github.com/user-attachments/assets/13206eb6-0e59-41da-9fc4-65db865f12e3">

**Comment by galletn** [comment]
@DeltaFox0018 Thanks for logging anyway, feel free to reopen when it should occur again!
