### ISSUE TITLE
Authorization header requires 'Credential' parameter

### ISSUE THREAD

**Issue by bertocea85** [galletn/iaqualink#4]
when I make a POST to https://prod.zodiac-io.com/devices/v2/xxxxxx/shadow it returns the following error:

 **Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header.**

With mitm proxy I see that it does a GET against https://r-api.iaqualink.net/v2/devices.json?user_id=xxx&signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&timestamp=1683216063

any idea? maybe it does a calculation of the signature and timestamp?

**Comment by bertocea85** [comment]
in both.
Both in Home assistant and through postman.
Home Assistant:
![image](https://github.com/galletn/iaqualink/assets/85909474/6546be6d-17bd-414d-b235-5668a8424b70)

**Comment by bertocea85** [comment]
this is mitm's capture
request
![image](https://github.com/galletn/iaqualink/assets/85909474/733393e5-af69-4c89-9754-6a48bbd4cb96)
Response
![image](https://github.com/galletn/iaqualink/assets/85909474/4745dd1c-baa5-4fad-8eb0-6fc3116193e7)

**Comment by galletn** [comment]
can you confirm in postman you send it like this: (it might be that your robot does not support this API and we need to find another one for you. What model of robot do you use?

![image](https://github.com/galletn/iaqualink/assets/21059110/553d90ad-9a01-4994-bcef-232e167ed639)

**Comment by galletn** [comment]
> this is mitm's capture request ![image](https://user-images.githubusercontent.com/85909474/240372517-733393e5-af69-4c89-9754-6a48bbd4cb96.png) Response ![image](https://user-images.githubusercontent.com/85909474/240373103-4745dd1c-baa5-4fad-8eb0-6fc3116193e7.png)

so the MITM is when you use the app rigth? seems that you are using V2 and that is the issue with you ...

**Comment by bertocea85** [comment]
> Puede confirmar en Postman que lo envía así: (puede ser que su robot no admita esta API y necesitemos encontrar otra para usted. ¿Qué modelo de robot utilizas?
> 
> ![imagen](https://user-images.githubusercontent.com/21059110/240375398-553d90ad-9a01-4994-bcef-232e167ed639.png)

Vortex OV5490 IQ ZODIAC
Mi captura de postman, 
![image](https://github.com/galletn/iaqualink/assets/85909474/8ccaaf15-cb42-400e-92ee-d9dfe58ce5f4)

**Comment by bertocea85** [comment]
then, the next one in mitm is this one
![image](https://github.com/galletn/iaqualink/assets/85909474/d3b84295-36cc-4577-b431-df391cd57524)
and this is Response
![image](https://github.com/galletn/iaqualink/assets/85909474/6b7afa4b-633f-4085-a21b-591efa906330)

**Comment by galletn** [comment]
the timestamp is just calculated as you can take from this site: https://current-timestamp.com/#result

but the signature one ... does it correspond to anything you get back from the login api?

**Comment by galletn** [comment]
good to see you got the control traces too, that way we are sure what we can expect to work. I'll try to add these too, but I would like to help you out on fixing the basics first.

For me and the others it seems to work, so it must be your robot that goes to the V2 that is a little different that we must tackle.

**Comment by bertocea85** [comment]
I have already looked to see if it was a login value. there is nothing similar.
in each call it uses a different signature and timestamp. then it does a get of the device to see the status.
![image](https://github.com/galletn/iaqualink/assets/85909474/dd99ee9a-7ccf-4631-877e-3315a74f4fde)
post 500 is when the device is offline

**Comment by bertocea85** [comment]
taking your code and testing it in visual studio, this is the answer.
Modifying the "Shadow" by values of the API here https://github.com/tekkamanendless/iaqualink, I get different values
![image](https://github.com/galletn/iaqualink/assets/85909474/cf6625f4-06e6-4d5d-babf-87c76e818cc3)

**Comment by galletn** [comment]
it seems that its using Google API's ... so after a little round of google:

https://developers.google.com/maps/documentation/maps-static/digital-signature#generate-signed-request

I'm not sure what values to use though to make this work ...

so your device is not supporting the shadow API right ... ? it says it does not belong to you when you use another value?

**Comment by galletn** [comment]
![image](https://github.com/galletn/iaqualink/assets/21059110/682eaace-1faf-48ed-98a1-b1f0be658a5b)

![image](https://github.com/galletn/iaqualink/assets/21059110/99e3402a-bd82-43b8-8134-aa719f1c466e)

![image](https://github.com/galletn/iaqualink/assets/21059110/126ef75a-353c-4349-8392-55e684b816e9)

**Comment by galletn** [comment]
after looking into the traces I see that I have the same behaviour as ppastur, it switches to websocket, so your robot seems to have total different approach ... will need other tactics...

**Comment by ppastur** [comment]
@bertocea85 - what model number do you have?

**Comment by ppastur** [comment]
> ![image](https://user-images.githubusercontent.com/21059110/240395978-682eaace-1faf-48ed-98a1-b1f0be658a5b.png)
> 
> ![image](https://user-images.githubusercontent.com/21059110/240396098-99e3402a-bd82-43b8-8134-aa719f1c466e.png)
> 
> ![image](https://user-images.githubusercontent.com/21059110/240396150-126ef75a-353c-4349-8392-55e684b816e9.png)

@galletn do you want me to try the same to see if I get the same issue with it returning offline?

**Comment by ppastur** [comment]
> the timestamp is just calculated as you can take from this site: https://current-timestamp.com/#result
> 
> but the signature one ... does it correspond to anything you get back from the login api?

Did you do that via websocket? if so, perhaps we didn't leave the socket open long enough to receive the stream showing updates.  My trace seemed to show plenty of updates from the device??  just a random thought?

**Comment by galletn** [comment]
> @galletn do you want me to try the same to see if I get the same issue with it returning offline?

yes might be handy to know if you get the same results

**Comment by ppastur** [comment]
> > @galletn do you want me to try the same to see if I get the same issue with it returning offline?
> 
> yes might be handy to know if you get the same results

Can you send me steps to reproduce - perhaps postman collection or code to run?

**Comment by bertocea85** [comment]
> > ![image](https://user-images.githubusercontent.com/21059110/240395978-682eaace-1faf-48ed-98a1-b1f0be658a5b.png)
> > ![image](https://user-images.githubusercontent.com/21059110/240396098-99e3402a-bd82-43b8-8134-aa719f1c466e.png)
> > ![image](https://user-images.githubusercontent.com/21059110/240396150-126ef75a-353c-4349-8392-55e684b816e9.png)
> 
> @galletn do you want me to try the same to see if I get the same issue with it returning offline?
@galletn @ppastur 
one question guys, where do you get the value for "Authorization"?

**Comment by ppastur** [comment]
@bertocea85 , authorization for me is the IdToken obtained in the post login

<img src="https://github.com/galletn/iaqualink/assets/91765182/569a3735-9bcc-4efc-bf1d-5c386776f6d2" width="90%" height="90%">

**Comment by galletn** [comment]
@bertocea85 still having issues with the latest release?

**Comment by bertocea85** [comment]
@galletn 
hello!! Sorry I've been away for a few days.
Now with the latest update, I see the entity and I see the buttons to start cleaning and stop, but it gives an error in the call to the service.

![image](https://github.com/user-attachments/assets/78f29123-f224-4902-ae84-5079c1e47a16)

Looking at the logs I see the following

Registrar: homeassistant.helpers.entity
Source: helpers/entity.py:944
First occurred: 12:19:11 (59 occurrences)
Last login: 13:17:10

Update for vacuum.robot_piscina fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 404, in get_device_status
    message = await websocket.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 244, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 681, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1296, in async_device_update
    await self.async_update()
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 254, in async_update
    data = await asyncio.wait_for(self.get_device_status(request), timeout=30)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by galletn** [comment]
@bertocea85 can you maybe change your password and send me over your credentials so that I can have a look? you can send them over to nicolas.gallet@skynet.be if you are willing. Thanks!

**Comment by bertocea85** [comment]
@galletn 
Hi! Sure! I just sent you an email with the details.
Thanks for your help!

**Comment by galletn** [comment]
@bertocea85 okay so I had a look and indeed your robot uses other api's as it is another device type. Can you have your robot being online? then I can see what happens when it is there...

<img width="711" alt="image" src="https://github.com/user-attachments/assets/3f68edca-9f87-4a9f-a21f-5ffd1bfd20fd">

**Comment by galletn** [comment]
the issue will be that it has very different behaviour then the other robots, as we can get the status it had previously even when its offline... so I also will need to think on how to handle that part ...

**Comment by bertocea85** [comment]
hello @galletn !!
Yes, I can put it in online mode, next Monday I will start it, I am not there right now to be able to turn it on

Thanks for your time

**Comment by bertocea85** [comment]
@galletn , is online now

**Comment by galletn** [comment]
@bertocea85 okay so took some first traces, I'll keep you posted once I have a first test version.

It will probably just be to report if its running yes/no, stop start & lift will be supportable, but I don't see sensor data nor in the app nor in the returns of the calls so it will be more basic info compared to the other robot models.

**Comment by bertocea85** [comment]
hello! @galletn 
Can I help you with anything else? Do you need any information or proof?

Thank you!

**Comment by galletn** [comment]
hi @bertocea85, can you leave the robot in the pool tonight? I would be able to continue my work on it.

So far what you could already test if it is correctly online/offline.

I'll upload the code in a jiffy in a new branch that supports the i2drobot.

So far the code here runs fine!

tonight I plan to create the stop start and get the status idle/running correctly, but for that I would prefer your robot to be for sure in the pool 😄 

![image](https://github.com/user-attachments/assets/8bfafb0c-88ce-4609-9c5a-de39fd3ab418)

**Comment by bertocea85** [comment]
Spectacular!!! Thank you for your time and dedication.
Yes, the robot is currently in the water and online, there is no plan to take it out, hahaha

**Comment by galletn** [comment]
@bertocea85 last update of the code now supports stop start on your robot, the time remaining and lift will be next! feel free to test already! https://github.com/galletn/iaqualink/tree/galletn-patch-4

**Comment by bertocea85** [comment]
hello!!

I have tested the code and it works perfectly!!! 
I can turn it on/off and see if it's cleaned.

Thank you @galletn

**Comment by galletn** [comment]
Excellent! I'll see what more I can do, but might be a busy week so depending on my schedule I'll add more functionality.

**Comment by galletn** [comment]
@bertocea85 can you confirm all is okay with the robot 😄 tested the return to base function and want to make sure it's fine before I test the time remaining while cleaning now.

I just updated the code, switching modes and getting the robot out of the water should work.

**Comment by bertocea85** [comment]
@galletn 
hello! Yes, the robot is fine and works perfectly!

**Comment by galletn** [comment]
great! I'm away for one week, upon my return I'll reach out again to continue the work on this!

**Comment by galletn** [comment]
hi @bertocea85 I pushed this to the main branch now as it seems okay! I did not find enough time yet to decode all info, so maybe I'll continue later on with the time remaining and the idle time. That is about all the info that I think we can still deduct. Except for that it should work now! Let me know!

**Comment by bertocea85** [comment]
@galletn, Works perfectly! thank you for your work and time
