### ISSUE TITLE
HAC Support ??

### ISSUE THREAD

**Issue by johntdyer** [galletn/iaqualink#8]
It doesn't appear this integration is actually supported by HACs.. Its missing manifiest and [hacs data](https://hacs.xyz/docs/publish/include/) so you cant even import it best I can tell.. I assume this is something ion the road map to address?

**Comment by galletn** [comment]
Dear John,

I installed it with HACS. It is in the list of integrations when you browse the HACS list. I updated it always over HACS too on my productive HA environment.

What is the issue for you?

**Comment by johntdyer** [comment]
I swear I was having issues earlier trying to add the repo to HACS, but now it works.... So I'll just go ahead and close this for the time being.  Thanks for your help !
